version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      DB_USER: "postgres"
      DB_PASS: "postgres"
  mongodb:
    image: 'bitnami/mongodb'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=barmee

